- hosts: all
  gather_facts: no
  # debugger: on_failed
  tasks:
    - yum: name=epel-release
      become: true
    - yum: 
        name:
          - zsh
          - vim
          - strace
          - cpuid
          - htop
          - git
      become: true
    - stat: path=.oh-my-zsh
      register: stat_results
    # - debug: var=stat_results
    - name: install oh-my-zsh
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended'
      when: not stat_results.stat.exists
    - name: zsh basic options
      blockinfile:
        path: .zshrc
        block: |
          setopt hist_ignore_all_dups
          setopt no_share_history
          bindkey \^U backward-kill-line
    - name: zsh theme
      replace:
        path: .zshrc
        regexp: 'ZSH_THEME="robbyrussell"'
        replace: 'ZSH_THEME="arrow"'
    - name: zsh plugins
      replace:
        path: .zshrc
        regexp: 'plugins=.*'
        replace: 'plugins=(git wd common-aliases history systemd extract tmux yum kubectl kube-ps1)'
    - name: 'zsh editor'
      lineinfile:
        path: .zshrc
        line: 'export EDITOR=vim'
    - name: 'zsh prompt'
      lineinfile:
        path: .zshrc
        regexp: '^PROMPT=.*'
        line: 'PROMPT="%m:$PROMPT\$(kube_ps1) "'
    - name: 'zsh disable kube-ps1'
      lineinfile:
        path: .zshrc
        line: 'kubeoff'

