- hosts: all
  gather_facts: no
  # debugger: on_failed
  tasks:
    - yum: name=epel-release
      become: true
    - yum: 
        name:
          - zsh
          - vim
          - strace
          - cpuid
          - htop
          - git
      become: true
    - stat: path=.oh-my-zsh
      register: stat_results
    # - debug: var=stat_results
    - shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended'
      when: not stat_results.stat.exists
    - blockinfile:
        path: .zshrc
        block: |
          setopt hist_ignore_all_dups
          setopt no_share_history
          bindkey \^U backward-kill-line
    - lineinfile:
        path: .zshrc
        regexp: 'ZSH_THEME="robbyrussell"'
        line: 'ZSH_THEME="arrow"'
    - lineinfile:
        path: .zshrc
        regexp: 'ZSH_THEME="robbyrussell"'
        line: 'ZSH_THEME="arrow"'
    - lineinfile:
        path: .zshrc
        regexp: 'plugins=.*'
        line: 'plugins=(git wd common-aliases history systemd extract tmux yum)'
    - lineinfile:
        path: .zshrc
        line: 'export EDITOR=vim'
