k9s:
  skin: gruvbox
  liveViewAutoRefresh: false
  screenDumpDir: /home/ppalucki/.local/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: true
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
  skipLatestRevCheck: false
  disablePodCounting: false
  # https://k9scli.io/topics/shell/
  # EDIT also: $XDG_DATA_HOME/k9s/clusters/clusterX/blee/config.yaml
  #  featureGates:
  #    nodeShell: true # => enable nodeShell for this context. Defaults to false
  shellPod:
    # image: nicolaka/netshoot
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
