k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  headless: true
  logoless: true
  crumbsless: true
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 5000
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: kind-gardener-local
  currentCluster: kind-gardener-local
  clusters:
    kind-gardener-local:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: aliases
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-root
