k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  headless: true
  logoless: true
  crumbsless: true
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 5000
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: garden-hc-dev--c5348773-haas-external
  currentCluster: garden-hc-dev--c5348773-haas-external
  clusters:
    garden-hc-dev--c5348773-haas-external:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - monitoring
        - default
      view:
        active: "no"
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-root
